### ISSUE TITLE
Refactoring of stack's `Stack.Types.Config` module

### ISSUE THREAD

**Issue by mpilgrem** [deepflowinc/guardian#8]
For your information, I have completed a major refactoring of the `stack` package's `Stack.Types.Config` module, which will be reflected in the next release of Stack (2.11.1).

Looking at what you import from `stack` (in module `Development.Guardian.Graph.Adapter.Stack.Enabled`):
* `HasBuildConfig` is now exported by `Stack.Types.BuildConfig`
* `HasSourceMap` is now exported by `Stack.Types.EnvConfig`

**Comment by konn** [comment]
Hi @mpilgrem, thank you for your information and sorry for late reply!
We are planning new release with the support for newer cabal and stack, so we will adopt to the change there.

**Comment by mpilgrem** [comment]
@konn, something to be aware of if you go beyond depending on stack-2.13.1 is that stack-2.15.1 has embraced OverloadedRecordDot, NoFieldSelectors and DuplicateRecordFields, allowing it to drop prefixes in field names.
